#!/usr/bin/env bash
set -euo pipefail

# Push branch and create PR for action updates.
# Input: outdated-actions-report.md
# Requires: GH_TOKEN, GH_REPO env vars

BRANCH_NAME="automation/update-github-actions"
ISSUE_TITLE="Security: Outdated GitHub Actions detected"
PR_TITLE="chore(core): update GitHub Actions to latest versions"

# Find issue number for linking
ISSUE_NUMBER=$(gh issue list --state open --search "in:title ${ISSUE_TITLE}" --json number --jq '.[0].number' 2>/dev/null || echo "")

# Close existing PR and delete branch if they exist
EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --state open --json number --jq '.[0].number' 2>/dev/null || echo "")
if [[ -n "$EXISTING_PR" ]]; then
  echo "Closing existing PR #${EXISTING_PR} to replace with updated version"
  gh pr close "$EXISTING_PR" --comment "Superseded by a new PR with updated changes." --delete-branch || true
fi

# Delete remote branch if it still exists
if git ls-remote --exit-code --heads origin "$BRANCH_NAME" > /dev/null 2>&1; then
  echo "Deleting existing remote branch"
  git push origin --delete "$BRANCH_NAME" || true
fi

# Push branch
git push -u origin "$BRANCH_NAME"

# Build PR body
PR_BODY="## Summary

Automatically updates GitHub Actions to their latest SHA-pinned versions.

$(cat outdated-actions-report.md)

---
${ISSUE_NUMBER:+Fixes #${ISSUE_NUMBER}}

*This PR was automatically generated by the [Check Action Versions](.github/workflows/check-action-versions.yml) workflow.*"

# Create PR targeting trunk
echo "Creating PR"
gh pr create \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  --label "security,dependencies" \
  --base trunk \
  --head "$BRANCH_NAME"
