blank_issues_enabled: true
contact_links:
  - name: Questions and Help
    url: https://github.com/nerdalytics/beacon/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/nerdalytics/beacon/blob/main/README.md
    about: Check the README and other documentation first.