name: Build Project

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build:
    strategy:
      matrix:
        node-version: ['20.x', '22.x']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.3.0
      with:
        node-version: '23.11.0'
    - id: cache-dependencies
      uses: actions/cache@v4.2.3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - name: Lint & format code
      run: npm run check
    - name: Build project
      run: npm run build
    - name: Test project
      run: npm run test
