name: Build & Test & Publish

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.3.0
      with:
        node-version: '23.11.0'
    - id: cache-dependencies
      uses: actions/cache@v4.2.3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-23.11.0-${{ hashFiles('**/package-lock.json') }}
    - name: Ensure cache exists
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: exit 1        
    - name: Check linting & code formatting
      run: npm run check
    - name: Build project
      run: npm run build:lts
    - name: Upload dist directory
      uses: actions/upload-artifact@v4.6.2
      with:
        name: dist
        path: dist/

  test:
    needs: build
    strategy:
      matrix:
        node-version: ['20.x', '22.x']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: actions/setup-node@v4.3.0
      with:
        node-version: ${{ matrix.node-version }}
    - id: cache-dependencies
      uses: actions/cache@v4.2.3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - name: Ensure cache exists
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: exit 1
    - name: Download dist directory
      uses: actions/upload-artifact@v4.6.2
      with:
        name: dist
        path: dist/
    - name: Test project
      run: SKIP_BUILD=true npm run test:lts

  publish-npm:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.3.0
        with:
          node-version: '23.11.0'
          registry-url: https://registry.npmjs.org/
      - id: cache-dependencies
        uses: actions/cache@v4.2.3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Ensure cache exists
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: exit 1
      - name: Download dist directory
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: dist/
      - run: npm pack
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_BEACON_PUBLISH_TOKEN}}
